### ISSUE TITLE
Architecture review and finalization

### ISSUE THREAD

**Issue by rajeevrra** [k8-proxy-glacier/p-k8-kubernetes-10k-pods#3]
Greetings  Libert & Chintan -, kindly help review the architecture and finalize in conjunction with comments provided by Dinis and track to closure by today.

**Comment by kcns008** [comment]
[p1-p-k8-kubernetes-10k-pods ( Kubernetes Architecture ( Rancher ) ) - 1st Oct 2020.pdf](https://github.com/k8-proxy/p-k8-kubernetes-10k-pods/files/5314532/p1-p-k8-kubernetes-10k-pods.Kubernetes.Architecture.Rancher.-.1st.Oct.2020.pdf)
![p1-p-k8-kubernetes-10k-pods K8-cluster Arch](https://user-images.githubusercontent.com/3204061/94858895-b6021400-0401-11eb-96fc-2d718ba2330e.png)
